name: 'Trufflehog Actions Scan ja'
description: 'Scan repository for secrets with basic trufflehog defaults in place for easy setup.'
author: 'ja'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  scanArguments:
    description: 'Argument options for scan.'
    required: false
branding:
  icon: 'shield'
  color: 'yellow'
